(function(){'use strict';
const KEY='lantern_long_night_v9';
const fresh=()=>({light:0,day:1,coins:4,mat:{paper:3,bamboo:2,thread:2,wax:2,ink:1,herb:2},parts:{paper:false,frame:false,thread:false,wick:false,message:false,pattern:false},message:'',kind:'carry',pattern:'moon',color:'gold',flame:false,flights:[],friends:[],explored:[],scene:'home',fx:'',muse:{connected:false,quality:0,steadiness:.5}});
let S=load(),toastTimer=null,fireflyTimer=null;
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'),{mat:Object.assign(fresh().mat,(JSON.parse(localStorage.getItem(KEY)||'{}').mat||{})),parts:Object.assign(fresh().parts,(JSON.parse(localStorage.getItem(KEY)||'{}').parts||{})),muse:Object.assign(fresh().muse,(JSON.parse(localStorage.getItem(KEY)||'{}').muse||{}))})}catch(e){return fresh()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch(e){}} function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){let e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.append(e)}e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2400)}
function nav(scene){S.scene=scene;save();render();scrollTo(0,0)}
function shell(title,kicker,body){return `<section class="screen"><button class="ghost back" onclick="nav('home')">← Home</button><p class="eyebrow">${kicker}</p><h1>${title}</h1>${body}</section>`}
function hud(){return `<header class="bar"><button class="ghost" onclick="nav('home')">🏮 <b>Lantern</b></button><div id="hud">✦ ${S.light} · 🪙 ${S.coins} · 📜 ${S.mat.paper} · 🎋 ${S.mat.bamboo}</div></header>`}
function render(){const app=document.getElementById('app');if(!app)return;let body='';if(S.scene==='home')body=home();else if(S.scene==='workshop')body=workshop();else if(S.scene==='message')body=message();else if(S.scene==='wander')body=wander();else if(S.scene==='sky')body=sky();else if(S.scene==='launch')body=launch();else if(S.scene==='quiet')body=quiet();else if(S.scene==='play')body=play();else body=home();app.innerHTML=hud()+body+`<div class="toast"></div>`;bind()}
function home(){return `<main><section class="hero"><div><p class="eyebrow">DAY ${S.day} · ${S.flights.length} LIGHTS IN YOUR SKY</p><h1>Make something beautiful.<br>Send it into the sky.</h1><p class="lead">Gather a few things. Build a paper lantern. Give it a little message. Light it. Then watch it become smaller and smaller until it joins the night.</p><div class="actions"><button class="primary" onclick="nav('workshop')">🏮 Make tonight's lantern</button><button class="ghost" onclick="nav('wander')">🌿 Wander first</button></div></div><div class="hero-sky"><div class="moon"></div><div class="distant-lights">${S.flights.slice(-8).map((_,i)=>`<i style="position:absolute;left:${10+i*11}%;top:${45+(i%3)*9}%;width:5px;height:8px;border-radius:50%;background:#f0cf82;box-shadow:0 0 14px #f0cf82"></i>`).join('')}</div><div class="hill"></div></div></section><section class="quick"><button onclick="nav('workshop')">🏮<b>Workshop</b><small>Build the next light</small></button><button onclick="nav('wander')">🌿<b>Wander</b><small>Gather and discover</small></button><button onclick="nav('play')">✦<b>Play</b><small>Little things to do</small></button><button onclick="nav('sky')">✨<b>Your Sky</b><small>${S.flights.length} lights released</small></button></section><section class="notice"><b>Tonight</b><span>${S.flights.length?'The sky is waiting for another little light.':'Your first lantern is waiting on the table.'}</span></section></main>`}
function lanternHTML(extra=''){return `<div class="lantern ${S.flame?'lit':''} ${extra}"><div class="top"></div><div class="body"></div><div class="frame"></div><div class="message">${esc(S.message)}</div><div class="flame"></div><div class="base"></div></div>`}
function workshop(){
 const p=S.parts;
 const items=[['paper','📜','Paper'],['frame','🎋','Frame'],['thread','🧵','Thread'],['wick','🕯️','Wick'],['pattern','✦','Pattern'],['message','💌','Message']];
 const cards=items.map(x=>`<button class="part ${p[x[0]]?'done':''}" onclick="partJump('${x[0]}')"><span>${p[x[0]]?'✓':x[1]}</span><b>${x[2]}</b></button>`).join('');
 const ready=allParts();
 const stage=p.message?'message':p.pattern?'pattern':p.wick?'wick':p.thread?'thread':p.frame?'frame':p.paper?'paper':'start';
 const fx=S.fx?` fx-${S.fx}`:'';
 return shell('The Workshop','MAKE IT BY HAND',`<div class="two"><section class="panel"><div class="workshop-scene ${stage}${fx}" id="workshopScene">
   <div class="stars"></div><div class="bench"></div>
   <div class="paper-piece"></div><div class="bamboo-piece b1"></div><div class="bamboo-piece b2"></div><div class="bamboo-piece b3"></div>
   <div class="thread-piece"></div><div class="wick-piece"></div><div class="paint-pattern pattern-${esc(S.pattern)}"></div>${lanternHTML()}
   <div class="work-label">${ready?(S.flame?'Warm and ready.':'All the pieces are here.'):`${nextPartLabel()}`}</div>
 </div>
 <div class="workplay" id="workplay">${workChallenge(stage)}</div>
 <div class="actions"><button class="ghost" onclick="nav('message')">💌 Message</button><button class="ghost" onclick="nav('wander')">🌿 Gather</button></div></section>
 <aside class="panel"><h2>Tonight's lantern</h2><p class="muted">This isn't a checklist. Each little action changes what is on the table.</p><div class="craft">${cards}</div><p class="muted" style="margin-top:18px">${ready?'Everything is ready. Take it outside.':'Touch the object in the work area to do the next little job.'}</p>${ready?`<button class="primary" onclick="nav('launch')">Take it to the field →</button>`:''}</aside></div>`);
}
function workChallenge(stage){
 if(stage==='start')return `<h3>Start with the paper</h3><p>Tap the sheet to make the first fold.</p><div class="playfield"><div class="fold-sheet" onclick="playFold(this)"></div></div>`;
 if(stage==='paper')return `<h3>Fold the paper</h3><p>One clean fold. Watch the flat sheet become the beginning of a lantern.</p><div class="playfield"><div class="fold-sheet" onclick="playFold(this)"></div><div class="work-success"><span>Folded.</span></div></div>`;
 if(stage==='frame')return `<h3>Build the frame</h3><p>Put the three bamboo pieces into place.</p><div class="playfield"><div class="frame-piece a" onclick="placeFrame(this)"></div><div class="frame-piece b" onclick="placeFrame(this)"></div><div class="frame-piece c" onclick="placeFrame(this)"></div><div class="work-success"><span>It holds.</span></div></div>`;
 if(stage==='thread')return `<h3>Tie it together</h3><p>Catch the loose loop and pull it snug.</p><div class="playfield"><div class="thread-loop" onclick="wrapThread(this)"></div><div class="work-success"><span>Nice and tight.</span></div></div>`;
 if(stage==='wick')return `<h3>Set the wick</h3><p>Tap the wick to seat it in the lantern.</p><div class="playfield"><div class="wick-target" onclick="placeWick(this)"></div><div class="work-success"><span>Centered.</span></div></div>`;
 if(stage==='pattern')return `<h3>Give it a face</h3><p>Pick one. The finished lantern keeps it.</p><div class="choice-grid" style="grid-template-columns:repeat(4,1fr)">${['moon','stars','waves','leaves'].map(o=>`<button class="choice" onclick="setPattern('${o}')"><strong>${({moon:'☾',stars:'✦',waves:'〰',leaves:'❧'})[o]}</strong><small>${o}</small></button>`).join('')}</div>`;
 if(stage==='message')return `<h3>Put something inside</h3><p>A few words are enough.</p><button class="primary" onclick="nav('message')">Open the message card →</button>`;
 return `<h3>Light it</h3><p>When you're ready, touch the spark.</p><div class="playfield"><div class="spark" onclick="igniteWorkshop(this)">✦</div><div class="work-success"><span>The lantern is glowing.</span></div></div>`;
}
function finishWorkshopPart(k,el){S.parts[k]=true;S.fx=k;S.light+=2;save();if(el){const ok=el.parentElement.querySelector('.work-success');if(ok)ok.classList.add('show')}setTimeout(()=>{S.fx='';save();render()},700)}
function playFold(el){if(S.parts.paper)return;el.classList.add('folded');finishWorkshopPart('paper',el)}
function placeFrame(el){if(el.classList.contains('set'))return;el.classList.add('set');const box=el.parentElement;if([...box.querySelectorAll('.frame-piece')].every(x=>x.classList.contains('set')))finishWorkshopPart('frame',el)}
function wrapThread(el){if(S.parts.thread)return;el.classList.add('wrapped');finishWorkshopPart('thread',el)}
function placeWick(el){if(S.parts.wick)return;el.classList.add('placed');finishWorkshopPart('wick',el)}
function igniteWorkshop(el){if(S.flame)return;el.classList.add('lit');S.flame=true;S.fx='light';S.light+=3;save();const ok=el.parentElement.querySelector('.work-success');if(ok)ok.classList.add('show');setTimeout(()=>{S.fx='';save();render()},850)}
function nextPartLabel(){if(!S.parts.paper)return'Fold the paper';if(!S.parts.frame)return'Shape the frame';if(!S.parts.thread)return'Tie the frame';if(!S.parts.wick)return'Set the wick';if(!S.parts.pattern)return'Choose a pattern';if(!S.parts.message)return'Write a message';return S.flame?'Take it outside →':'Light the lantern'}
function allParts(){return Object.values(S.parts).every(Boolean)}
function partJump(k){if(k==='message'){nav('message');return}if(k==='pattern'){choosePattern();return}doPart(k)}
function doPart(force){
 let k=force||(!S.parts.paper?'paper':!S.parts.frame?'frame':!S.parts.thread?'thread':!S.parts.wick?'wick':!S.parts.pattern?'pattern':!S.parts.message?'message':!S.flame?'light':'launch');
 const cost={paper:['paper',1],frame:['bamboo',2],thread:['thread',1],wick:['wax',1],pattern:['ink',1]}[k];
 if(cost&&S.mat[cost[0]]<cost[1]){toast('You need more '+cost[0]+'. Try a little walk.');nav('wander');return}
 if(k==='message'){nav('message');return}
 if(k==='pattern'){choosePattern();return}
 if(k==='light'){S.flame=true;S.fx='light';S.light+=3;save();render();setTimeout(()=>{S.fx='';save();render()},900);return}
 if(k==='launch'){nav('launch');return}
 S.mat[cost[0]]-=cost[1];S.parts[k]=true;S.fx=k;S.light+=2;save();render();
 setTimeout(()=>{S.fx='';save();render()},900);
 toast({paper:'You fold the paper into a lantern body.',frame:'The bamboo frame snaps into place.',thread:'The thread wraps and the frame holds.',wick:'The wick settles in the center.',pattern:'The pattern blooms across the paper.'}[k]||'Done.');
}
function choosePattern(){const opts=['moon','stars','waves','leaves'];const labels={moon:'☾',stars:'✦ ✧',waves:'〰〰',leaves:'❧ ❧'};const colors=['gold','rose','mint','sky'];document.getElementById('app').innerHTML=hud()+shell('Choose its face','A LITTLE PERSONALITY',`<section class="panel"><div class="choice-grid">${opts.map(o=>`<button class="choice ${S.pattern===o?'selected':''}" onclick="setPattern('${o}')"><strong style="font-size:30px">${labels[o]}</strong><small>${o}</small></button>`).join('')}</div><div class="actions">${colors.map(c=>`<button class="choice ${S.color===c?'selected':''}" style="min-height:auto" onclick="setColor('${c}')">● ${c}</button>`).join('')}</div><button class="primary" onclick="nav('workshop')">Keep it →</button></section>`)}
function setPattern(x){S.pattern=x;S.parts.pattern=true;save();render()}function setColor(x){S.color=x;save();render()}
function message(){return shell('Give it a few words','NOTHING PERFECT REQUIRED',`<section class="panel"><p class="lead">A name. A thank-you. A wish. Something to carry. Something you don't want to hold tonight. Or one completely ordinary word.</p><div class="choice-grid">${[['carry','🌱','Carry','something worth keeping alive'],['thank','💛','Thank','something worth honoring'],['setdown','🍂','Set down','something you can leave here for tonight'],['wish','🌟','Wish','something you hope finds its way forward']].map(x=>`<button class="choice ${S.kind===x[0]?'selected':''}" onclick="S.kind='${x[0]}';render()"><strong>${x[1]} ${x[2]}</strong><small>${x[3]}</small></button>`).join('')}</div><textarea id="msg" maxlength="180" placeholder="Write as much or as little as you want…">${esc(S.message)}</textarea><div class="actions"><button class="ghost" onclick="nav('workshop')">Back</button><button class="primary" onclick="saveMessage()">Fold it inside →</button></div></section>`)}
function saveMessage(){S.message=document.getElementById('msg').value.trim();S.parts.message=true;S.light+=3;save();toast('The message is tucked safely inside.');nav('workshop')}
function wander(){return shell('Wander','LOOKING FOR SMALL THINGS',`<section class="panel"><p class="lead">The world gives you reasons to walk without requiring you to hurry.</p><div class="resource-grid">${[['meadow','🌾','Meadow','paper + herbs'],['grove','🎋','Bamboo Grove','bamboo + thread'],['pond','🌙','Moonpond','paper + wax'],['hill','☼','Dawn Hill','rare finds']].map(x=>`<button class="choice resource" onclick="gather('${x[0]}')"><div><strong style="font-size:28px">${x[1]}</strong><h2>${x[2]}</h2><p>${x[3]}</p></div><small>Walk here →</small></button>`).join('')}</div><div class="notice"><b>Friends</b><span>${S.friends.length?'Someone you know may be wandering too.':'There are tiny lives out there. You may meet one if you keep your eyes open.'}</span></div><button class="primary" onclick="encounter()">🐾 Look around</button></section>`)}
function gather(a){const loot={meadow:{paper:1,herb:1},grove:{bamboo:1,thread:1},pond:{paper:1,wax:1},hill:{ink:1,herb:1}}[a];for(const k in loot)S.mat[k]+=loot[k];S.light++;if(!S.explored.includes(a))S.explored.push(a);save();toast('You found '+Object.entries(loot).map(([k,v])=>v+' '+k).join(' and ')+'.');render()}
function encounter(){if(!S.friends.length){S.friends.push({name:'Mori',species:'moth-fox',bond:0,visits:0,seed:4831})}else{const f=S.friends[0];f.bond++;f.visits++;S.light+=2}save();toast(S.friends[0].name+' stayed for a while.');render()}
function sky(){const lights=S.flights.map((f,i)=>`<div class="sky-lantern" style="left:${8+(i*31)%84}%;top:${16+(i*23)%72}%" title="${esc(f.text||'a quiet light')}"></div>`).join('');return shell('Your Sky','EVERY LIGHT STAYS',`<div class="two"><section class="panel"><div class="skyview"><div class="moon"></div>${lights}</div></section><aside class="panel"><h2>${S.flights.length} lights</h2><p class="muted">They don't need to mean the same thing forever. They can simply be part of the night.</p>${S.flights.slice().reverse().map((f,i)=>`<div class="part done"><b>Flight ${S.flights.length-i}</b><small>${esc(f.kind)} · ${esc(f.text||'quiet')}</small></div>`).join('')||'<p class="muted">Your first one is waiting.</p>'}<button class="primary" onclick="nav('workshop')">Make another →</button></aside></div>`)}
function launch(){return shell('The Launching Field','TAKE YOUR TIME',`<section class="panel"><div class="flight" id="flight"><div class="stars"></div><div class="flight-lantern">${lanternHTML()}</div><div class="flight-caption">${S.message?`Inside: “${esc(S.message)}”`:'No words required.'}</div></div><div class="actions" style="justify-content:center"><button class="primary" onclick="release()">Release the lantern ↑</button><button class="ghost" onclick="nav('workshop')">Not yet</button></div></section>`)}
function release(){if(!allParts()||!S.flame){toast('It still needs to be finished and lit.');nav('workshop');return}const f=document.getElementById('flight');f.classList.add('go');setTimeout(()=>{S.flights.push({day:S.day,kind:S.kind,text:S.message,pattern:S.pattern,color:S.color});S.light+=10;S.coins+=2;S.day++;S.parts=fresh().parts;S.message='';S.flame=false;S.kind='carry';save();render();toast('A new light has joined your sky.')},7200)}
function play(){return shell('Little Night Games','PLAY FOR THE JOY OF IT',`<div class="choice-grid"><button class="choice" onclick="fireflies()"><strong>✦ Firefly Catch</strong><small>Catch three wandering lights.</small></button><button class="choice" onclick="tending()"><strong>🔥 Hold the Flame</strong><small>Keep a small flame steady through a changing breeze.</small></button><button class="choice" onclick="patternMemory()"><strong>✧ Remember the Pattern</strong><small>Watch three lights, then find them again.</small></button><button class="choice" onclick="nav('quiet')"><strong>🌙 Quiet Flight</strong><small>A longer, softer lantern space.</small></button></div>`)}
function fireflies(){let hits=0;function round(){if(hits>=3){S.light+=5;save();toast('The meadow gave you a little light.');nav('play');return}const x=12+Math.random()*76,y=15+Math.random()*70;document.getElementById('app').innerHTML=hud()+shell('Firefly Catch','FOLLOW THE LITTLE LIGHT',`<section class="panel"><div class="mini"><button class="firefly" style="left:${x}%;top:${y}%" onclick="window._ff()">✦</button></div><p class="muted">${hits+1} of 3</p></section>`);window._ff=()=>{hits++;round()}}round()}
function tending(){let t=12,score=0;document.getElementById('app').innerHTML=hud()+shell('Hold the Flame','A SMALL ATTENTION GAME',`<section class="panel"><div class="mini"><div style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-size:65px;filter:drop-shadow(0 0 25px #f0cf82)">🔥</div></div><p id="timer">${t}s · 0 good moments</p><button class="primary" onclick="score++">Tap gently when you notice the flame.</button></section>`);clearInterval(fireflyTimer);fireflyTimer=setInterval(()=>{t--;const e=document.getElementById('timer');if(e)e.textContent=`${t}s · ${score} good moments`;if(t<=0){clearInterval(fireflyTimer);S.light+=score;save();toast('The flame held.');nav('play')}},1000)}
function patternMemory(){const seq=[0,1,2].sort(()=>Math.random()-.5);let ready=false,idx=0;document.getElementById('app').innerHTML=hud()+shell('Remember the Pattern','WATCH · THEN PLAY',`<section class="panel"><p id="pm">Watch the three lights.</p><div class="choice-grid">${['✦','☾','✧'].map((x,i)=>`<button class="choice" onclick="window._pm(${i})"><strong style="font-size:38px">${x}</strong></button>`).join('')}</div></section>`);let n=0;const tm=setInterval(()=>{n++;document.getElementById('pm').textContent=n<4?'Light '+n+' of 3…':'Your turn.';if(n>=4){clearInterval(tm);ready=true}},650);window._pm=i=>{if(!ready)return;if(i!==seq[idx]){toast('The pattern slipped away.');nav('play');return}idx++;if(idx===3){S.light+=6;save();toast('You remembered it.');nav('play')}}}
function quiet(){return shell('Quiet Flight','MUSE 2 · OPTIONAL',`<section class="panel zen"><div class="orb">${lanternHTML('lit')}</div><h2>Let the lantern drift.</h2><p class="lead">Stay with the light for as long as you like. If Muse is connected, its signal can gently influence the glow. Nothing needs to be measured as good or bad.</p><div class="actions" style="justify-content:center"><button class="primary" onclick="startQuiet()">Begin 5 minutes</button><button class="ghost" onclick="connectMuse()">${S.muse.connected?'Muse connected':'Connect Muse 2'}</button></div></section>`)}
function startQuiet(){let t=300;document.getElementById('app').innerHTML=hud()+shell('Quiet Flight','THE LANTERN IS HERE',`<section class="panel zen"><div class="orb">${lanternHTML('lit')}</div><h2 id="qt">5:00</h2><p id="qx" class="lead">Notice the light. If attention wanders, let it come back.</p><button class="ghost" onclick="nav('home')">Leave quietly</button></section>`);const tm=setInterval(()=>{t--;const q=document.getElementById('qt'),x=document.getElementById('qx');if(!q){clearInterval(tm);return}q.textContent=Math.floor(t/60)+':'+String(t%60).padStart(2,'0');if(t<200)x.textContent='There is nothing to fix. Let the lantern drift.';if(t<80)x.textContent='The sky is still here. You can come back whenever you want.';if(t<=0){clearInterval(tm);q.textContent='The lantern is still here.'}},1000)}
function connectMuse(){S.muse.connected=!S.muse.connected;S.muse.quality=S.muse.connected?.85:0;save();toast(S.muse.connected?'Muse is ready for feedback.':'Muse disconnected.');nav('quiet')}
function bind(){}
globalThis.nav=nav;globalThis.S=S;globalThis.render=render;globalThis.doPart=doPart;globalThis.partJump=partJump;globalThis.setPattern=setPattern;globalThis.setColor=setColor;globalThis.saveMessage=saveMessage;globalThis.gather=gather;globalThis.encounter=encounter;globalThis.release=release;globalThis.fireflies=fireflies;globalThis.tending=tending;globalThis.patternMemory=patternMemory;globalThis.startQuiet=startQuiet;globalThis.connectMuse=connectMuse;globalThis.playFold=playFold;globalThis.placeFrame=placeFrame;globalThis.wrapThread=wrapThread;globalThis.placeWick=placeWick;globalThis.igniteWorkshop=igniteWorkshop;
function boot(){try{render()}catch(err){console.error('Lantern boot failed:',err);const app=document.getElementById('app');if(app)app.innerHTML=`<header class="bar"><div class="brand">🏮 <strong>Lantern</strong><span>The Long Night</span></div><div id="hud">✦ ${S.light} · 🪙 ${S.coins}</div></header><main><section class="hero"><div><p class="eyebrow">A LITTLE NIGHT RITUAL</p><h1>Make something beautiful.<br>Send it into the sky.</h1><p class="lead">The night is still here. Start with a little paper lantern.</p><button class="primary" onclick="globalThis.nav('workshop')">🏮 Start making</button></div><div class="hero-sky"><div class="moon"></div><div class="distant-lights"></div><div class="hill"></div></div></section></main>`}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
