/* Lantern UI + procedural SVG sprites + optional Muse bridge. */
(()=>{
const G=Lantern, A=document.getElementById('app');let screen='home',modal=null,game=null;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function sprite(c,size=88){const h=c.hue;const body={round:`<circle cx="50" cy="54" r="30"/>`,bean:`<ellipse cx="50" cy="55" rx="28" ry="34"/>`,moth:`<ellipse cx="50" cy="55" rx="18" ry="25"/><ellipse cx="29" cy="51" rx="18" ry="24"/><ellipse cx="71" cy="51" rx="18" ry="24"/>`,fox:`<path d="M22 42 28 18 42 29 58 29 72 18 78 42Q82 78 50 80Q18 78 22 42Z"/>`,frog:`<path d="M19 48Q18 25 33 29Q50 18 67 29Q82 25 81 48Q80 80 50 80Q20 80 19 48Z"/>`,bird:`<ellipse cx="50" cy="55" rx="30" ry="23"/><path d="M21 53Q5 44 18 36L36 49Z"/>`,blob:`<path d="M20 62Q15 34 32 31Q44 13 60 28Q82 29 80 55Q78 80 52 80Q24 82 20 62Z"/>`}[c.body];
const ears={none:'',leaf:'<path d="M29 31 18 12Q35 15 40 32Z"/><path d="M71 31 82 12Q65 15 60 32Z"/>',round:'<circle cx="29" cy="27" r="10"/><circle cx="71" cy="27" r="10"/>',long:'<path d="M28 36 20 8 40 29Z"/><path d="M72 36 80 8 60 29Z"/>',horn:'<path d="M31 31 35 10 45 30Z"/><path d="M69 31 65 10 55 30Z"/>'}[c.ears];
const eyes={dot:'<circle cx="39" cy="53" r="4"/><circle cx="61" cy="53" r="4"/>',wide:'<circle cx="38" cy="52" r="7"/><circle cx="62" cy="52" r="7"/><circle cx="39" cy="50" r="2"/><circle cx="63" cy="50" r="2"/>',sleep:'<path d="M34 53q5 5 10 0M56 53q5 5 10 0" fill="none" stroke="#18201e" stroke-width="4" stroke-linecap="round"/>',spark:'<path d="M38 49v10m-5-5h10M62 49v10m-5-5h10" stroke="#18201e" stroke-width="3" stroke-linecap="round"/>'}[c.eyes];
const marks={plain:'',spot:'<circle cx="67" cy="68" r="6" opacity=".25"/>',stripe:'<path d="M30 68q20 10 40 0" fill="none" stroke="#fff" opacity=".18" stroke-width="6"/>',star:'<path d="m50 37 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z" fill="#fff" opacity=".4"/>',moon:'<path d="M58 34q-12 9 0 20 9 7 14-1-2 18-20 15-15-3-12-18 3-13 18-16Z" fill="#fff" opacity=".28"/>'}[c.mark];
return `<svg class="sprite" width="${size}" height="${size}" viewBox="0 0 100 100" style="--h:${h}"><g fill="hsl(${h} 48% 62%)" stroke="#18201e" stroke-width="3" stroke-linejoin="round">${ears}${body}</g>${marks}<g>${eyes}</g><path d="M44 65q6 5 12 0" fill="none" stroke="#18201e" stroke-width="3" stroke-linecap="round"/></svg>`}
function layout(inner,active='home'){A.innerHTML=`<div class="shell"><header><button class="brand" onclick="UI.go('home')"><span class="brand-lantern">🏮</span><span>Lantern</span></button><div class="topstats"><span>✨ ${G.S.light}</span><span>🪙 ${G.S.coins}</span><span>🔥 ${G.S.streak}</span></div></header><main>${inner}</main><nav class="dock"><button class="${active==='home'?'on':''}" onclick="UI.go('home')">⌂<small>Home</small></button><button class="${active==='map'?'on':''}" onclick="UI.go('map')">✦<small>Explore</small></button><button class="play" onclick="UI.play()">🏮<small>Play</small></button><button class="${active==='friends'?'on':''}" onclick="UI.go('friends')">♡<small>Friends</small></button><button class="${active==='more'?'on':''}" onclick="UI.go('more')">⋯<small>More</small></button></nav></div>`}
function home(){let c=G.friends?.[0]||G.S.friends[0];let room=G.rooms[Math.min(G.S.world,G.rooms.length-1)];layout(`<section class="hero"><div><p class="eyebrow">THE LONG NIGHT</p><h1>Keep a little light on.</h1><p class="sub">A tiny world to wander when the night feels large.</p><button class="primary" onclick="UI.play()">Play a little <span>→</span></button></div><div class="heroart"><div class="moon">☾</div><div class="hill h1"></div><div class="hill h2"></div><div class="lanternbig">🏮</div></div></section><section class="daily"><div><span class="pill">TODAY</span><h2>${G.S.streak>1?'The village remembers you.':'The village is awake.'}</h2><p>${room.desc}</p></div><button class="secondary" onclick="UI.explore()">Wander</button></section><section class="cards"><div class="card"><div class="cardicon">✨</div><b>${G.S.light} light</b><span>World level ${G.S.world+1}</span></div><div class="card"><div class="cardicon">${c?'🧸':'🌱'}</div><b>${G.S.friends.length} friend${G.S.friends.length===1?'':'s'}</b><span>${c?esc(c.name)+' is nearby.':'Someone may be waiting.'}</span></div></section><section class="sectionhead"><h2>Small things count</h2><span>always</span></section><div class="micro"><button onclick="UI.play('return')">🏠 <b>Come back</b><small>Find five ordinary anchors</small></button><button onclick="UI.play('weather')">🌦️ <b>Weather Catch</b><small>Name the sky without fixing it</small></button></div>`,'home')}
function map(){let rs=G.rooms;layout(`<section class="pagehead"><p class="eyebrow">WORLD MAP</p><h1>Where the night goes</h1><p>Every place opens by playing, not by being perfect.</p></section><div class="map">${rs.map((r,i)=>`<button class="maproom ${r.unlocked()?'open':'locked'}" ${r.unlocked()?'onclick="UI.enter('+i+')"':''}><span class="roomnum">${r.unlocked()?i+1:'·'}</span><div><b>${r.name}</b><small>${r.desc}</small></div><span>${r.unlocked()?'→':'🔒'}</span></button>`).join('')}</div><div class="tip">There is no losing here. If you need to leave, leaving is part of the game.</div>`,'map')}
function enter(i){const r=G.rooms[i];if(!r.unlocked())return;const games={village:'return',explore:'weather',steady:'return',story:'echo',meaning:'weather',connect:'return',carry:'echo'};game=G.games[games[r.tag]]?G.games[games[r.tag]]():G.games.return();game.room=i;screen='mini';renderMini()}
function play(type){game=G.games[type||['weather','return','echo'][Math.floor(Math.random()*3)]]();screen='mini';renderMini()}
function renderMini(){const g=game;if(g.type==='weather')return miniWeather(g);if(g.type==='return')return miniReturn(g);if(g.type==='echo')return miniEcho(g)}
function miniWeather(g){layout(`<section class="gamehead"><button class="back" onclick="UI.go('home')">←</button><span class="pill">MINI-GAME</span><h1>${g.title}</h1><p>${g.prompt}</p></section><div class="weatherstage"><div class="weatherword">${g.target[0]}</div><p>Which word belongs with it?</p><div class="choicegrid">${g.opts.map(o=>`<button onclick="UI.weather('${o[1]}','${g.target[1]}')">${esc(o[0])}<span>${o[1]}</span></button>`).join('')}</div></div>`,'home')}
function miniReturn(g){layout(`<section class="gamehead"><button class="back" onclick="UI.go('home')">←</button><span class="pill">MINI-GAME</span><h1>${g.title}</h1><p>${g.prompt}</p></section><div class="returnstage"><div class="lanternfloat">🏮</div><div class="anchors">${g.items.map((x,i)=>`<button onclick="UI.anchor(${i})">${({warmth:'🧣',water:'💧',sound:'🎵',ground:'🪨',light:'✨',company:'🫶'})[x]}<span>${x}</span></button>`).join('')}</div><p class="quiet">You only need three. The rest can wait.</p></div>`,'home')}
function miniEcho(g){layout(`<section class="gamehead"><button class="back" onclick="UI.go('home')">←</button><span class="pill">MINI-GAME</span><h1>${g.title}</h1><p>${g.prompt}</p></section><div class="echostage">${g.cards.map((c,i)=>`<button onclick="UI.echo(${i},'${c[1]}')"><b>${esc(c[0])}</b><small>tap to place</small></button>`).join('')}</div>`,'home')}
function result(title,text,skill){const r=G.reward(title,skill);G.unlockIf();layout(`<section class="result"><div class="burst">✨</div><p class="eyebrow">NICE WORK</p><h1>${title}</h1><p>${text}</p><div class="rewardrow"><span>✨ +${r.light} light</span><span>🪙 +${r.coins}</span></div><button class="primary" onclick="UI.go('map')">See what opened <span>→</span></button><button class="textbtn" onclick="UI.play()">Play again</button></section>`,'home')}
function explore(){const x=G.explore();modal={title:x.friend?'A new friend!':'A little something',body:`<div class="found">${sprite(x.creature,140)}</div><h2>${esc(x.creature.name)}</h2><p>${x.friend?`${esc(x.creature.name)} decided you seemed nice. They are staying nearby.`:'You found a curious little creature. It vanished into the moss, but left something behind.'}</p>`};renderModal()}
function friends(){layout(`<section class="pagehead"><p class="eyebrow">COMPANIONS</p><h1>Your little people</h1><p>Friends don't need you to explain yourself.</p></section>${G.S.friends.length?`<div class="friendgrid">${G.S.friends.map(c=>`<article class="friend">${sprite(c,120)}<h2>${esc(c.name)}</h2><small>${c.body} · ${c.mark}</small></article>`).join('')}</div>`:`<div class="empty"><div>🌱</div><h2>No friends yet.</h2><p>Wander around. The world is full of small introductions.</p><button class="primary" onclick="UI.explore()">Wander</button></div>`}`,'friends')}
function more(){layout(`<section class="pagehead"><p class="eyebrow">MORE</p><h1>Your lantern</h1><p>Everything stays on this device unless you choose to export it.</p></section><div class="settings"><button onclick="UI.journal()">📖 <b>Notebook</b><small>Private local journal</small></button><button onclick="UI.muse()">🧠 <b>Muse bridge</b><small>${G.S.muse.connected?'connected':'optional sensor mode'}</small></button><button onclick="UI.export()">⇩ <b>Export save</b><small>Download your local game state</small></button><button onclick="UI.importPrompt()">⇧ <b>Import save</b><small>Restore a local backup</small></button><button onclick="UI.about()">ⓘ <b>About the design</b><small>Why the world works this way</small></button></div>`,'more')}
function journal(){modal={title:'Notebook',body:`<textarea id="note" class="note" placeholder="A thought, a tiny thing you noticed, something you want to remember…"></textarea><button class="primary" onclick="UI.saveNote()">Keep it</button><div class="notes">${G.S.journal.slice(0,8).map(n=>`<article><small>${new Date(n.t).toLocaleString()}</small><p>${esc(n.text)}</p></article>`).join('')}</div>`};renderModal()}
let M=null,museTimer=null;
function muse(){
 const supported=!!navigator.bluetooth;
 const m=G.S.muse;
 modal={title:'Muse 2',body:`<p><b>Optional hardware mode.</b> Lantern connects directly to a Muse 2 over Bluetooth. Sensor data stays in this page; it is not uploaded anywhere.</p><div class="musebox"><div class="musedot ${m.connected?'live':''}"></div><b>${m.connected?'Muse 2 connected':'Muse 2 not connected'}</b><small id="museStatus">${m.connected?'Live sensor stream.':'Web Bluetooth: '+(supported?'available':'not available in this browser')}</small></div><div class="musemetrics"><div><b id="mq">${Math.round(m.quality*100)}%</b><small>signal</small></div><div><b id="ms">${Math.round(m.steadiness*100)}%</b><small>steadiness</small></div><div><b id="mm">${Math.round(m.motion*100)}%</b><small>motion</small></div><div><b id="mb">${m.battery==null?'—':Math.round(m.battery)+'%'}</b><small>battery</small></div></div><div class="museactions"><button class="primary" onclick="UI.connectMuse()" ${m.connected?'disabled':''}>Connect Muse 2</button><button class="secondary" onclick="UI.disconnectMuse()" ${m.connected?'':'disabled'}>Disconnect</button></div><p class="fine">The game uses signal quality, steadiness and movement as game inputs. It does not interpret EEG as a diagnosis, mood score, or measure of emotional health.</p><p class="fine">For direct browser Bluetooth, use Chrome or Edge on Android/Windows and open Lantern from HTTPS (such as your GitHub Pages site). Safari does not provide the required Web Bluetooth API.</p>`};renderModal();startMuseTicker()}
function startMuseTicker(){clearInterval(museTimer);museTimer=setInterval(()=>{const q=document.getElementById('mq'),s=document.getElementById('ms'),mo=document.getElementById('mm'),b=document.getElementById('mb');if(!q)return;const m=G.S.muse;q.textContent=Math.round(m.quality*100)+'%';s.textContent=Math.round(m.steadiness*100)+'%';mo.textContent=Math.round(m.motion*100)+'%';b.textContent=m.battery==null?'—':Math.round(m.battery)+'%';},300)}
async function connectMuse(){
 if(!M)M=new LanternMuse2();
 M.onState=(state)=>{G.S.muse.connected=state==='connected';const e=document.getElementById('museStatus');if(e)e.textContent=state==='connected'?'Live sensor stream.':state==='disconnected'?'Disconnected.':state+'…';if(state==='connected')toast('Muse 2 connected.');};
 M.onFrame=(f)=>{G.museFrame(f)};
 try{await M.connect();}catch(e){toast(e.message||'Muse connection failed.');const st=document.getElementById('museStatus');if(st)st.textContent=e.message||'Connection failed.'}
 muse();
}
async function disconnectMuse(){if(M)await M.disconnect();G.S.muse.connected=false;G.save();muse()}
function demoMuse(){G.S.muse.connected=true;G.museFrame({quality:.9,steadiness:.7,motion:.08,battery:100});muse()}
function about(){modal={title:'About the design',body:`<p><b>Lantern is a game first.</b> Its mechanics quietly practice noticing, returning attention, making room for mixed feelings, connection, meaning, and taking the next small step.</p><p>There are no grief scores, no diagnosis, no recovered-memory mechanics, and no requirement to disclose personal history.</p><p>The world is local-first: progress and notebook entries use browser storage. No account, API, CDN, analytics, or remote service is required.</p><p class="fine">This is a game prototype, not a substitute for professional care. If playing makes you feel unsafe or unable to orient, pause and use the support available to you.</p>`};renderModal()}
function renderModal(){if(!modal){return}document.body.insertAdjacentHTML('beforeend',`<div class="modalshade" onclick="if(event.target===this)UI.closeModal()"><div class="modal"><button class="close" onclick="UI.closeModal()">×</button><h1>${modal.title}</h1>${modal.body}</div></div>`)}
function closeModal(){document.querySelector('.modalshade')?.remove();modal=null}
function weather(chosen,target){if(chosen===target){G.S.stats.returnWins++;result('You caught it.','The point was not to change the weather. You noticed it, and that was enough.','ground')}else result('No wrong weather.','You noticed a word that did not fit this time. The lantern stays on.','flex')}
function anchor(i){if(!game.picked)game.picked=[];game.picked.push(game.items[i]);if(game.picked.length>=3)result('You came back.','Warmth, water, sound, ground, light, company — ordinary things can be powerful anchors.','ground');else{const b=document.querySelector('.quiet');if(b)b.textContent=`${3-game.picked.length} more, if you want them.`}}
function echo(i,type){if(type==='story')result('You left room for the story.','A thought can feel true without being the only possible future.','flex');else result('You gave it a name.','Facts, feelings, and stories can sit beside one another without having to fight.','meaning')}
function saveNote(){let e=document.getElementById('note');if(G.journal(e.value)){closeModal();toast('Kept in your local notebook.')}else toast('Nothing to save.')}
function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function exportSave(){const blob=new Blob([G.exportSave()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lantern-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importPrompt(){let i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{let f=i.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{if(G.importSave(r.result)){toast('Save restored.');location.reload()}else toast('That save could not be read.')};r.readAsText(f)};i.click()}
function go(x){closeModal();screen=x;({home,map:home,friends,more}[x]||home)();if(x==='map')map()}
function start(){home()}
window.UI={go,play,enter,explore,friends,more,journal,muse,about,closeModal,weather,anchor,echo,saveNote,export:exportSave,importPrompt,demoMuse,connectMuse,disconnectMuse};window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});window.UI.start=start;start();
})();
