/* Lantern UI — game-first, touch-first, no external assets. */
const UI=(()=>{
let screen='home',area='home',toastTimer=0,mini=null,raf=0;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const icons={wood:'🪵',stone:'🪨',herb:'🌿',seed:'🌱',thread:'🧵',star:'⭐',berry:'🫐',tea:'🍵',fish:'🐟'};
function start(){render();}
function nav(s){screen=s;render()}
function render(){cancelAnimationFrame(raf);const app=$('app');if(!app)return;app.innerHTML=`<header class="top"><button class="brand" onclick="UI.nav('home')"><span class="brandlamp">✦</span><span>Lantern</span></button><div class="meters"><span>✨ ${Lantern.S.light}</span><span>🪙 ${Lantern.S.coins}</span><span>⚡ ${Lantern.S.energy}/${Lantern.S.maxEnergy}</span></div><button class="iconbtn" onclick="UI.nav('journal')">☰</button></header><main>${screen==='home'?home():screen==='world'?world():screen==='friends'?friends():screen==='house'?house():screen==='meditate'?meditate():screen==='journal'?journal():about()}</main><div id="toast" class="toast"></div>`;bind();drawWorld();}
function home(){const S=Lantern.S,q=S.quests.daily||{};return `<section class="hero"><div class="moon">☾</div><div><p class="eyebrow">DAY ${S.day} · ${S.streak} night streak</p><h1>Good evening, Keeper.</h1><p class="lede">The little world is awake. What sounds good tonight?</p></div></section><section class="home-grid"><button class="bigcard play" onclick="UI.nav('world')"><span class="cardart">🌲 ✦ 🐾</span><strong>Go wandering</strong><small>Explore, find things, meet someone.</small></button><button class="bigcard" onclick="UI.nav('house')"><span class="cardart">🏡 🌱 🏮</span><strong>Tend the little house</strong><small>Garden, craft, tidy, make tea, rest.</small></button><button class="bigcard" onclick="UI.nav('friends')"><span class="cardart">🐇 🦋 🐸</span><strong>Visit friends</strong><small>See what your companions are up to.</small></button><button class="bigcard" onclick="UI.nav('meditate')"><span class="cardart lanternart">🏮</span><strong>Lantern quiet</strong><small>A Muse-aware guided session, or just sit with the light.</small></button></section><section class="quest"><div><span class="eyebrow">TONIGHT'S LITTLE QUEST</span><h2>${esc(q.label||'Take it easy')}</h2><p>${q.done||0}/${q.goal||1} · reward ${q.reward||0} light</p></div><div class="questbar"><i style="width:${Math.min(100,((q.done||0)/(q.goal||1))*100)}%"></i></div></section><section class="soft-note">No perfect route. Wandering counts. Resting counts. Coming back counts.</section>`}
function world(){const unlocked=Lantern.areas.filter(a=>Lantern.canArea(a.id));return `<section class="screenhead"><button class="back" onclick="UI.nav('home')">← home</button><p class="eyebrow">THE WORLD</p><h1>Where shall we wander?</h1><p>Each outing costs one lantern-energy. You can always come home.</p></section><div class="map">${Lantern.areas.map(a=>{const open=Lantern.canArea(a.id);return `<button class="area ${open?'open':'locked'} ${area===a.id?'selected':''}" onclick="UI.pickArea('${a.id}')" ${open?'':'disabled'}><span class="areaicon">${a.kind==='water'?'◒':a.kind==='market'?'✹':a.kind==='echo'?'♧':a.kind==='garden'?'❀':a.kind==='summit'?'☼':a.kind==='home'?'⌂':'♣'}</span><strong>${esc(a.name)}</strong><small>${open?a.desc:`Unlocks at ${a.need} light`}</small></button>`}).join('')}</div><section class="wanderbox"><div class="scene"><div class="scene-moon">☾</div><div class="stars">✦ · ✧ · ⋆ · ✦</div><div id="spritefield"></div><div class="ground"></div></div><div class="wander-controls"><h2>${esc((Lantern.areas.find(a=>a.id===area)||Lantern.areas[1]).name)}</h2><p>${esc((Lantern.areas.find(a=>a.id===area)||Lantern.areas[1]).desc)}</p><button class="primary" onclick="UI.wander()">Wander here <span>−1 ⚡</span></button></div></section>`}
function friends(){return `<section class="screenhead"><button class="back" onclick="UI.nav('home')">← home</button><p class="eyebrow">COMPANIONS</p><h1>The friends you've met</h1><p>They have their own little lives. You don't need to perform for them.</p></section>${Lantern.S.friends.length?`<div class="friends">${Lantern.S.friends.map(friendCard).join('')}</div>`:`<div class="empty"><div>🐾</div><h2>Nobody yet</h2><p>Go wandering. Someone is bound to be hiding behind a mushroom.</p><button class="primary" onclick="UI.nav('world')">Go find somebody</button></div>`}`}
function friendCard(f){return `<article class="friend"><div class="friendvisual" style="--h:${f.hue}deg"><div class="creature-svg">${sprite(f)}</div></div><div class="friendinfo"><div class="eyebrow">${esc(f.temperament)}</div><h2>${esc(f.name)}</h2><p>Loves ${esc(f.like)} · met ${f.met} times</p><div class="bond"><span>bond</span><i>${'●'.repeat(Math.min(5,Math.ceil(f.bond/2)))}${'○'.repeat(Math.max(0,5-Math.ceil(f.bond/2)))}</i></div><div class="actions"><button onclick="UI.friend('${f.id}','sit')">Sit</button><button onclick="UI.friend('${f.id}','play')">Play</button><button onclick="UI.friend('${f.id}','talk')">Talk</button><button onclick="UI.friend('${f.id}','help')">Help</button><button onclick="UI.friend('${f.id}','gift')">Gift</button></div></div></article>`}
function house(){const S=Lantern.S,ready=S.home.plants.filter(p=>p.stage>=3).length;return `<section class="screenhead"><button class="back" onclick="UI.nav('home')">← home</button><p class="eyebrow">YOUR LITTLE HOUSE</p><h1>Tend the things you keep.</h1><p>Maintenance is allowed to be gentle. Nothing decays while you're away.</p></section><section class="house-scene"><div class="house-art"><div class="roof">⌂</div><div class="window">✦</div><div class="plantrow">${S.home.plants.map(p=>p.stage===0?'🌱':p.stage===1?'🌿':p.stage===2?'🌷':'🫐').join(' ')||'·  ·  ·'}</div><div class="porch">${S.home.bench?'🪑':'▱'} ${S.home.decor.map(()=> '⭐').join('')}</div></div><div class="house-stats"><span>Garden ${S.home.garden}</span><span>Lantern ${S.home.lantern}</span><span>Clean ${S.home.clean}/3</span></div></section><div class="actiongrid"><button onclick="UI.tend('garden')">🌱 Plant seed</button><button onclick="UI.tend('water')">💧 Water garden</button><button onclick="UI.tend('lantern')">🏮 Tend lantern</button><button onclick="UI.tend('clean')">🧹 Sweep</button><button onclick="UI.tend('sit')">🪑 Sit a while</button><button onclick="UI.harvest()">🫐 Harvest ${ready?`(${ready})`:''}</button></div><section class="craft"><h2>Workbench</h2><div class="recipes"><button onclick="UI.craft('tea')">🍵 Tea <small>🌿1 🫐1</small></button><button onclick="UI.craft('lanternCharm')">⭐ Star charm <small>🧵1 ⭐1</small></button><button onclick="UI.craft('seedPacket')">🌱 Seed packet <small>🫐1 🌿1</small></button><button onclick="UI.craft('stoneBench')">🪑 Bench <small>🪨3 🪵2</small></button></div></section><section class="inventory"><h2>Pockets</h2>${Object.entries(S.inventory).map(([k,v])=>`<span>${icons[k]||'•'} ${v}</span>`).join('')}</section>`}
function meditate(){return `<section class="screenhead"><button class="back" onclick="UI.nav('home')">← home</button><p class="eyebrow">THE LANTERN ROOM</p><h1>Make the little light steady.</h1><p>A quiet interactive session. Muse can make the lantern respond, but it is completely optional.</p></section><div class="med-card"><div class="big-lantern" id="biglantern">🏮</div><div class="med-orb" id="medorb"></div><div class="med-time" id="medtime">5:00</div><p id="medhint">Choose a pace. Nothing to achieve.</p><div class="med-buttons"><button class="primary" onclick="UI.medStart(5)">5 minutes</button><button onclick="UI.medStart(10)">10</button><button onclick="UI.medStart(20)">20</button></div><div class="musebar"><span id="museStatus">Muse: ${Lantern.S.muse.connected?'connected':'not connected'}</span><button onclick="MuseUI&&MuseUI.connect&&MuseUI.connect()">Connect Muse 2</button></div></div><div class="soft-note">The visual feedback responds to signal quality and steadiness trends. It does not diagnose emotion.</div>`}
function journal(){const S=Lantern.S;return `<section class="screenhead"><button class="back" onclick="UI.nav('home')">← home</button><p class="eyebrow">KEEPER'S NOTEBOOK</p><h1>A place for words, if you want them.</h1></section><textarea id="note" class="note" placeholder="Anything you want to leave here…"></textarea><button class="primary" onclick="UI.saveNote()">Put it in the notebook</button><div class="notes">${S.journal.map(n=>`<article><time>${new Date(n.t).toLocaleString()}</time><p>${esc(n.text)}</p></article>`).join('')||'<p class="muted">The notebook is empty.</p>'}</div><section class="settings"><h2>Local save</h2><p>Everything stays in this browser.</p><button onclick="UI.downloadSave()">Export save</button><label class="filebtn">Import save<input type="file" accept="application/json" onchange="UI.importFile(this)"></label><button class="danger" onclick="UI.reset()">Reset local world</button></section>`}
function about(){return `<section class="screenhead"><button class="back" onclick="UI.nav('home')">← home</button><p class="eyebrow">ABOUT</p><h1>A little world, built to be lived in.</h1><p>Lantern is a cozy game first. Its deeper design quietly practices noticing, returning, connection, restoration, meaning and self-kindness.</p></section><div class="aboutcards"><article><h2>Local first</h2><p>No account, server, analytics, cloud save, CDN or runtime dependency.</p></article><article><h2>Muse 2</h2><p>Optional sensor feedback can influence the lantern and meditation experience. Signal is processed locally.</p></article><article><h2>Never a test</h2><p>There are no failure states for feeling bad, wandering away, resting, or changing your mind.</p></article></div>`}
function sprite(f){return `<svg viewBox="0 0 100 100" aria-label="${esc(f.name)}"><defs><linearGradient id="g${f.id}" x1="0" x2="1"><stop offset="0" stop-color="hsl(${f.hue} 65% 70%)"/><stop offset="1" stop-color="hsl(${(f.hue+45)%360} 60% 58%)"/></linearGradient></defs><ellipse cx="50" cy="72" rx="28" ry="19" fill="url(#g${f.id})"/><circle cx="50" cy="52" r="24" fill="url(#g${f.id})"/>${f.ears==='long'?'<path d="M31 38 L24 10 Q35 16 40 34 M69 38 L76 10 Q65 16 60 34" fill="url(#g'+f.id+')"/>':f.ears==='leaf'?'<path d="M34 39 Q16 23 29 14 Q43 24 41 40 M66 39 Q84 23 71 14 Q57 24 59 40" fill="url(#g'+f.id+')"/>':''}<circle cx="42" cy="51" r="4" fill="#101817"/><circle cx="58" cy="51" r="4" fill="#101817"/><circle cx="40.5" cy="49.5" r="1.5" fill="#fff"/><circle cx="56.5" cy="49.5" r="1.5" fill="#fff"/>${f.mark==='star'?'<text x="50" y="70" text-anchor="middle" font-size="13">★</text>':f.mark==='spot'?'<circle cx="62" cy="67" r="5" fill="rgba(255,255,255,.35)"/>':''}<path d="M45 61 Q50 66 55 61" fill="none" stroke="#17211f" stroke-width="2" stroke-linecap="round"/></svg>`}
function bind(){window.UI=UI;}
function pickArea(id){area=id;render()}
function wander(){const out=Lantern.wander(area);if(out.error)return toast('Your little lantern is tired. Go home and rest.');showOutcome(out)}
function showOutcome(o){let body='';if(o.type==='creature'){const c=o.new?o.creature:o.friend;if(o.new){Lantern.addFriend(c);body=`<div class="out-sprite">${sprite(c)}</div><h2>You found ${esc(c.name)}!</h2><p>A ${esc(c.temperament)} little ${esc(c.body)} who likes ${esc(c.like)}. They seem willing to know you.</p><button class="primary" onclick="UI.closeOutcome();UI.nav('friends')">Say hello</button>`}else body=`<div class="out-sprite">${sprite(c)}</div><h2>${esc(c.name)} was here.</h2><p>They remember you. Their mood is ${esc(c.mood)}.</p><button class="primary" onclick="UI.closeOutcome();UI.friend('${c.id}','sit')">Sit together</button>`}
else if(o.type==='gather'||o.type==='cache')body=`<div class="out-icon">${icons[o.item]}</div><h2>You found ${o.qty} ${esc(o.item)}.</h2><p>Into the pockets it goes. Useful little things accumulate.</p><button class="primary" onclick="UI.closeOutcome()">Nice.</button>`;
else if(o.type==='view')body=`<div class="out-icon">✦</div><h2>You notice something.</h2><p>${esc(o.view)}.</p><button class="primary" onclick="UI.closeOutcome()">Stay a moment</button>`;
else if(o.type==='choice')body=`<div class="out-icon">☾</div><h2>${esc(o.choice.q)}</h2><div class="choicegrid">${o.choice.a.map((x,i)=>`<button onclick="UI.resolveChoice('${x[1]}')">${esc(x[0])}</button>`).join('')}</div>`;
else if(o.type==='mini')body=miniGame(o.mini);
openModal(body)}
function miniGame(kind){if(kind==='firefly')return `<div class="out-icon">🪲</div><h2>Firefly Catch</h2><p>Tap the glow when it appears. Misses don't matter.</p><div class="fireflygame" id="fireflygame"><button id="fly" onclick="UI.catchFly()">✦</button></div><p id="ministatus">Ready?</p>`;if(kind==='pond')return `<div class="out-icon">🐟</div><h2>Moonpond</h2><p>Tap a ripple when it reaches the ring.</p><div class="pondgame" onclick="UI.pondTap(event)"><i></i><b></b></div><p id="ministatus">Wait for it…</p>`;if(kind==='lantern')return `<div class="out-icon">🏮</div><h2>Lantern Trim</h2><p>Tap when the little marker is in the soft middle.</p><input class="range" id="trim" type="range" min="0" max="100" value="50"><button class="primary" onclick="UI.trimLantern()">Trim the wick</button><p id="ministatus">The sweet spot is around the middle.</p>`;return `<div class="out-icon">◐</div><h2>Fact, feeling, story</h2><p>Which bucket does this belong in?</p><div class="sorting"><div class="sortcard">“My chest feels tight.”</div><button onclick="UI.sort('ground')">Sensation</button><button onclick="UI.sort('connect')">Feeling</button><button onclick="UI.sort('meaning')">Story</button></div><p id="ministatus"></p>`}
function openModal(html){let m=document.createElement('div');m.id='modal';m.className='modal';m.innerHTML=`<div class="modalshade" onclick="UI.closeOutcome()"></div><div class="modalbox">${html}<button class="close" onclick="UI.closeOutcome()">×</button></div>`;document.body.appendChild(m);if(document.getElementById('fireflygame'))setTimeout(moveFly,400);if(document.querySelector('.pondgame'))startPond()}
function closeOutcome(){const m=$('modal');if(m)m.remove()}
function resolveChoice(skill){Lantern.resolveChoice(skill);closeOutcome();toast('A little light for the road.');render()}
function friend(id,a){const x=Lantern.friendAction(id,a);if(x?.error)return toast(x.error);toast(x.msg);render()}
function tend(x){const r=Lantern.tend(x);if(r.error)return toast(r.error);toast(r.msg);render()}
function craft(x){const r=Lantern.craft(x);if(r.error)return toast(r.error);toast(r.msg);render()}
function harvest(){const r=Lantern.harvest();if(r.error)return toast(r.error);toast(r.msg);render()}
function catchFly(){Lantern.playMini('firefly');$('ministatus').textContent='Caught! +5 light. Another one is already hiding.';moveFly()}
function moveFly(){const f=$('fly');if(!f)return;f.style.left=(8+Math.random()*78)+'%';f.style.top=(10+Math.random()*72)+'%'}
function startPond(){const p=document.querySelector('.pondgame');if(p)p.classList.add('rippling')}
function pondTap(e){Lantern.playMini('pond');$('ministatus').textContent='A silver splash. +6 light.'}
function trimLantern(){const v=+$('trim').value;const d=Math.abs(v-52);const gain=d<10?10:d<20?6:3;Lantern.gain(gain,2,'ground');$('ministatus').textContent=`The lantern settles. +${gain} light.`}
function sort(skill){Lantern.resolveChoice(skill);$('ministatus').textContent='Nice noticing. There is a difference between what happens, what you feel, and what your mind says about it.'}
function saveNote(){const t=$('note').value;if(!t.trim())return toast('Nothing to save.');Lantern.S.journal.unshift({t:Date.now(),text:t.trim()});Lantern.S.journal=Lantern.S.journal.slice(0,100);Lantern.save();toast('Saved locally.');render()}
function downloadSave(){const b=new Blob([Lantern.exportSave()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='lantern-save.json';a.click();URL.revokeObjectURL(a.href)}
function importFile(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{if(Lantern.importSave(r.result)){toast('World restored.');render()}else toast('That save could not be read.')};r.readAsText(f)}
function reset(){if(confirm('Reset this local Lantern world?')){Lantern.reset();render()}}
let medTimer=null,medEnd=0;
function medStart(minutes){clearInterval(medTimer);medEnd=Date.now()+minutes*60000;const hint=['Let the light be soft.','Notice the room around you.','If attention wanders, let it come back.','Nothing needs to be forced.','Stay as long as feels useful.'];$('medhint').textContent=hint[Math.floor(Math.random()*hint.length)];medTimer=setInterval(()=>{const left=Math.max(0,medEnd-Date.now());$('medtime').textContent=`${Math.floor(left/60000)}:${String(Math.floor(left/1000)%60).padStart(2,'0')}`;const m=Lantern.S.muse;const power=.35+.65*(m.connected?m.steadiness:.6);$('biglantern').style.transform=`scale(${.95+power*.12})`;$('medorb').style.opacity=.2+power*.7;if(left<=0){clearInterval(medTimer);Lantern.S.stats.calmSessions++;Lantern.gain(10,5,'ground');$('medhint').textContent='The session is complete. You can carry on, or stay a little longer.'}},500);}
function toast(t){const x=$('toast');if(!x)return;clearTimeout(toastTimer);x.textContent=t;x.classList.add('show');toastTimer=setTimeout(()=>x.classList.remove('show'),2600)}
function drawWorld(){if(screen!=='world')return;const f=$('spritefield');if(!f)return;f.innerHTML=Lantern.S.friends.slice(0,8).map((x,i)=>`<button class="roamer" style="left:${x.position.x}%;top:${x.position.y}%;--h:${x.hue}deg" onclick="UI.friend('${x.id}','sit')">${sprite(x)}</button>`).join('')}
return{start,nav,pickArea,wander,resolveChoice,closeOutcome,friend,tend,craft,harvest,catchFly,pondTap,trimLantern,sort,saveNote,downloadSave,importFile,reset,medStart};
})();
