/* Lantern UI. Game-first, touch-first, local-first. */
(()=>{
const G=Lantern,A=document.getElementById('app');let screen='home',modal=null,game=null,M=null,museTimer=null,med=null,audio=null;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function sprite(c,size=88){const h=c.hue;const body={round:`<circle cx="50" cy="54" r="30"/>`,bean:`<ellipse cx="50" cy="55" rx="28" ry="34"/>`,moth:`<ellipse cx="50" cy="55" rx="18" ry="25"/><ellipse cx="29" cy="51" rx="18" ry="24"/><ellipse cx="71" cy="51" rx="18" ry="24"/>`,fox:`<path d="M22 42 28 18 42 29 58 29 72 18 78 42Q82 78 50 80Q18 78 22 42Z"/>`,frog:`<path d="M19 48Q18 25 33 29Q50 18 67 29Q82 25 81 48Q80 80 50 80Q20 80 19 48Z"/>`,bird:`<ellipse cx="50" cy="55" rx="30" ry="23"/><path d="M21 53Q5 44 18 36L36 49Z"/>`,blob:`<path d="M20 62Q15 34 32 31Q44 13 60 28Q82 29 80 55Q78 80 52 80Q24 82 20 62Z"/>`}[c.body];
const ears={none:'',leaf:'<path d="M29 31 18 12Q35 15 40 32Z"/><path d="M71 31 82 12Q65 15 60 32Z"/>',round:'<circle cx="29" cy="27" r="10"/><circle cx="71" cy="27" r="10"/>',long:'<path d="M28 36 20 8 40 29Z"/><path d="M72 36 80 8 60 29Z"/>',horn:'<path d="M31 31 35 10 45 30Z"/><path d="M69 31 65 10 55 30Z"/>'}[c.ears];
const eyes={dot:'<circle cx="39" cy="53" r="4"/><circle cx="61" cy="53" r="4"/>',wide:'<circle cx="38" cy="52" r="7"/><circle cx="62" cy="52" r="7"/><circle cx="39" cy="50" r="2"/><circle cx="63" cy="50" r="2"/>',sleep:'<path d="M34 53q5 5 10 0M56 53q5 5 10 0" fill="none" stroke="#18201e" stroke-width="4" stroke-linecap="round"/>',spark:'<path d="M38 49v10m-5-5h10M62 49v10m-5-5h10" stroke="#18201e" stroke-width="3" stroke-linecap="round"/>'}[c.eyes];
const marks={plain:'',spot:'<circle cx="67" cy="68" r="6" opacity=".25"/>',stripe:'<path d="M30 68q20 10 40 0" fill="none" stroke="#fff" opacity=".18" stroke-width="6"/>',star:'<path d="m50 37 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z" fill="#fff" opacity=".4"/>',moon:'<path d="M58 34q-12 9 0 20 9 7 14-1-2 18-20 15-15-3-12-18 3-13 18-16Z" fill="#fff" opacity=".28"/>'}[c.mark];
return `<svg class="sprite" width="${size}" height="${size}" viewBox="0 0 100 100" style="--h:${h}"><g fill="hsl(${h} 48% 62%)" stroke="#18201e" stroke-width="3" stroke-linejoin="round">${ears}${body}</g>${marks}<g>${eyes}</g><path d="M44 65q6 5 12 0" fill="none" stroke="#18201e" stroke-width="3" stroke-linecap="round"/></svg>`}
function museBadge(){const m=G.S.muse;return `<span class="musebadge ${m.connected?'live':''}"><i></i>${m.connected?'Muse live':'Muse'}</span>`}
function layout(inner,active='home'){A.innerHTML=`<div class="shell"><header><button class="brand" onclick="UI.go('home')"><span class="brand-lantern">🏮</span><span>Lantern</span></button><div class="topstats"><span>✨ ${G.S.light}</span><span>🪙 ${G.S.coins}</span><span>🔥 ${G.S.streak}</span>${museBadge()}</div></header><main>${inner}</main><nav class="dock"><button class="${active==='home'?'on':''}" onclick="UI.go('home')">⌂<small>Home</small></button><button class="${active==='map'?'on':''}" onclick="UI.go('map')">✦<small>Explore</small></button><button class="play" onclick="UI.play()">🏮<small>Play</small></button><button class="${active==='friends'?'on':''}" onclick="UI.go('friends')">♡<small>Friends</small></button><button class="${active==='more'?'on':''}" onclick="UI.go('more')">⋯<small>More</small></button></nav></div>`}
function home(){let c=G.S.friends[0],room=G.rooms[Math.min(G.S.world,G.rooms.length-1)],m=G.S.muse;layout(`<section class="hero"><div><p class="eyebrow">THE LONG NIGHT</p><h1>Keep a little light on.</h1><p class="sub">A tiny world to wander when the night feels large.</p><button class="primary" onclick="UI.play()">Play a little <span>→</span></button><button class="secondary musehome" onclick="UI.meditate()">🌙 Quiet with the lantern</button></div><div class="heroart"><div class="moon">☾</div><div class="hill h1"></div><div class="hill h2"></div><div class="lanternhalo" id="museHalo"></div><div class="lanternbig" id="museLantern">🏮</div><div class="musewhisper" id="museWhisper">${m.connected?'The lantern can feel your steadiness.':'The lantern is waiting.'}</div></div></section><section class="daily"><div><span class="pill">TODAY</span><h2>${G.S.streak>1?'The village remembers you.':'The village is awake.'}</h2><p>${room.desc}</p></div><button class="secondary" onclick="UI.explore()">Wander</button></section><section class="cards"><div class="card"><div class="cardicon">✨</div><b>${G.S.light} light</b><span>World level ${G.S.world+1}</span></div><div class="card"><div class="cardicon">${c?'🧸':'🌱'}</div><b>${G.S.friends.length} friend${G.S.friends.length===1?'':'s'}</b><span>${c?esc(c.name)+' is nearby.':'Someone may be waiting.'}</span></div></section><section class="sectionhead"><h2>Small things count</h2><span>always</span></section><div class="micro"><button onclick="UI.play('return')">🏠 <b>Come back</b><small>Find five ordinary anchors</small></button><button onclick="UI.play('weather')">🌦️ <b>Weather Catch</b><small>Name the sky without fixing it</small></button></div>`,'home');applyMuseVisual();}
function map(){layout(`<section class="pagehead"><p class="eyebrow">WORLD MAP</p><h1>Where the night goes</h1><p>Every place opens by playing, not by being perfect.</p></section><div class="map">${G.rooms.map((r,i)=>`<button class="maproom ${r.unlocked()?'open':'locked'}" ${r.unlocked()?`onclick="UI.enter(${i})"`:''}><span class="roomnum">${r.unlocked()?i+1:'·'}</span><div><b>${r.name}</b><small>${r.desc}</small></div><span>${r.unlocked()?'→':'🔒'}</span></button>`).join('')}</div><div class="tip">There is no losing here. If you need to leave, leaving is part of the game.</div>`,'map')}
function enter(i){const r=G.rooms[i];if(!r.unlocked())return;const games={village:'return',explore:'weather',steady:'return',story:'echo',meaning:'weather',connect:'return',carry:'echo'};game=G.games[games[r.tag]]?G.games[games[r.tag]]():G.games.return();game.room=i;screen='mini';renderMini()}
function play(type){game=G.games[type||['weather','return','echo'][Math.floor(Math.random()*3)]]();screen='mini';renderMini()}
function renderMini(){if(game.type==='weather')return miniWeather(game);if(game.type==='return')return miniReturn(game);if(game.type==='echo')return miniEcho(game)}
function miniWeather(g){layout(`<section class="gamehead"><button class="back" onclick="UI.go('home')">←</button><span class="pill">MINI-GAME</span><h1>${g.title}</h1><p>${g.prompt}</p></section><div class="weatherstage"><div class="weatherword">${g.target[0]}</div><p>Which word belongs with it?</p><div class="choicegrid">${g.opts.map(o=>`<button onclick="UI.weather('${o[1]}','${g.target[1]}')">${esc(o[0])}<span>${o[1]}</span></button>`).join('')}</div></div>`,'home')}
function miniReturn(g){layout(`<section class="gamehead"><button class="back" onclick="UI.go('home')">←</button><span class="pill">MINI-GAME</span><h1>${g.title}</h1><p>${g.prompt}</p></section><div class="returnstage"><div class="lanternfloat">🏮</div><div class="anchors">${g.items.map((x,i)=>`<button onclick="UI.anchor(${i})">${({warmth:'🧣',water:'💧',sound:'🎵',ground:'🪨',light:'✨',company:'🫶'})[x]}<span>${x}</span></button>`).join('')}</div><p class="quiet">You only need three. The rest can wait.</p></div>`,'home')}
function miniEcho(g){layout(`<section class="gamehead"><button class="back" onclick="UI.go('home')">←</button><span class="pill">MINI-GAME</span><h1>${g.title}</h1><p>${g.prompt}</p></section><div class="echostage">${g.cards.map((c,i)=>`<button onclick="UI.echo(${i},'${c[1]}')"><b>${esc(c[0])}</b><small>tap to place</small></button>`).join('')}</div>`,'home')}
function result(title,text,skill){const r=G.reward(title,skill);G.unlockIf();layout(`<section class="result"><div class="burst">✨</div><p class="eyebrow">NICE WORK</p><h1>${title}</h1><p>${text}</p><div class="rewardrow"><span>✨ +${r.light} light</span><span>🪙 +${r.coins}</span></div><button class="primary" onclick="UI.go('map')">See what opened <span>→</span></button><button class="textbtn" onclick="UI.play()">Play again</button></section>`,'home')}
function explore(){const x=G.explore();modal={title:x.friend?'A new friend!':'A little something',body:`<div class="found">${sprite(x.creature,140)}</div><h2>${esc(x.creature.name)}</h2><p>${x.friend?`${esc(x.creature.name)} decided you seemed nice. They are staying nearby.`:'You found a curious little creature. It vanished into the moss, but left something behind.'}</p>`};renderModal()}
function friends(){layout(`<section class="pagehead"><p class="eyebrow">COMPANIONS</p><h1>Your little people</h1><p>Friends don't need you to explain yourself.</p></section>${G.S.friends.length?`<div class="friendgrid">${G.S.friends.map(c=>`<article class="friend">${sprite(c,120)}<h2>${esc(c.name)}</h2><small>${c.body} · ${c.mark}</small></article>`).join('')}</div>`:`<div class="empty"><div>🌱</div><h2>No friends yet.</h2><p>Wander around. The world is full of small introductions.</p><button class="primary" onclick="UI.explore()">Wander</button></div>`}`,'friends')}
function more(){layout(`<section class="pagehead"><p class="eyebrow">MORE</p><h1>Your lantern</h1><p>Everything stays on this device unless you choose to export it.</p></section><div class="settings"><button onclick="UI.meditate()">🌙 <b>Lantern Meditation</b><small>Guided practice with optional Muse 2 feedback</small></button><button onclick="UI.journal()">📖 <b>Notebook</b><small>Private local journal</small></button><button onclick="UI.muse()">🧠 <b>Muse 2</b><small>${G.S.muse.connected?'connected · live feedback':'connect optional sensor'}</small></button><button onclick="UI.export()">⇩ <b>Export save</b><small>Download your local game state</small></button><button onclick="UI.importPrompt()">⇧ <b>Import save</b><small>Restore a local backup</small></button><button onclick="UI.about()">ⓘ <b>About the design</b><small>Why the world works this way</small></button></div>`,'more')}
function journal(){modal={title:'Notebook',body:`<textarea id="note" class="note" placeholder="A thought, a tiny thing you noticed, something you want to remember…"></textarea><button class="primary" onclick="UI.saveNote()">Keep it</button><div class="notes">${G.S.journal.slice(0,8).map(n=>`<article><small>${new Date(n.t).toLocaleString()}</small><p>${esc(n.text)}</p></article>`).join('')}</div>`};renderModal()}
function muse(){const supported=!!navigator.bluetooth,m=G.S.muse;modal={title:'Muse 2',body:`<p><b>Optional sensor mode.</b> Muse 2 connects directly to this page. Sensor data is processed locally.</p><div class="musebox"><div class="musedot ${m.connected?'live':''}"></div><b>${m.connected?'Muse 2 connected':'Muse 2 not connected'}</b><small id="museStatus">${m.connected?'Live sensor stream.':'Web Bluetooth: '+(supported?'available':'not available here')}</small></div><div class="musemetrics"><div><b id="mq">${Math.round(m.quality*100)}%</b><small>signal</small></div><div><b id="ms">${Math.round(m.steadiness*100)}%</b><small>steadiness</small></div><div><b id="mm">${Math.round(m.motion*100)}%</b><small>motion</small></div><div><b id="mb">${m.battery==null?'—':Math.round(m.battery)+'%'}</b><small>battery</small></div></div><div class="musewave" id="museWave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="museactions"><button class="primary" onclick="UI.connectMuse()" ${m.connected?'disabled':''}>Connect Muse 2</button><button class="secondary" onclick="UI.disconnectMuse()" ${m.connected?'':'disabled'}>Disconnect</button><button class="secondary" onclick="UI.meditate()">Open meditation</button></div><p class="fine">The game uses signal quality, movement and a conservative steadiness trend for feedback. It does not treat EEG as a diagnosis or an emotional truth.</p><p class="fine">Direct browser Bluetooth requires a Web-Bluetooth browser and HTTPS. Chrome/Edge on Android and Edge/Chrome on Windows are the intended targets.</p>`};renderModal();startMuseTicker()}
function startMuseTicker(){clearInterval(museTimer);museTimer=setInterval(()=>{const m=G.S.muse,q=document.getElementById('mq'),s=document.getElementById('ms'),mo=document.getElementById('mm'),b=document.getElementById('mb');if(!q)return;q.textContent=Math.round(m.quality*100)+'%';s.textContent=Math.round(m.steadiness*100)+'%';mo.textContent=Math.round(m.motion*100)+'%';b.textContent=m.battery==null?'—':Math.round(m.battery)+'%';const wave=document.getElementById('museWave');if(wave)wave.style.setProperty('--steadiness',m.steadiness);},250)}
async function connectMuse(){if(!M)M=new LanternMuse2();M.onState=state=>{G.S.muse.connected=state==='connected';G.S.muse.last=Date.now();G.save();const e=document.getElementById('museStatus');if(e)e.textContent=state==='connected'?'Live sensor stream.':state==='disconnected'?'Disconnected.':state+'…';if(state==='connected')toast('Muse 2 connected.');applyMuseVisual()};M.onFrame=f=>{G.museFrame(f);applyMuseVisual();if(screen==='meditate')updateMeditationMuse()};try{await M.connect()}catch(e){toast(e.message||'Muse connection failed.');const st=document.getElementById('museStatus');if(st)st.textContent=e.message||'Connection failed.'}muse()}
async function disconnectMuse(){if(M)await M.disconnect();G.S.muse.connected=false;G.save();applyMuseVisual();muse()}
function applyMuseVisual(){const m=G.S.muse,lan=document.getElementById('museLantern'),halo=document.getElementById('museHalo'),w=document.getElementById('museWhisper');if(!lan)return;const st=m.connected?m.steadiness:.35;lan.style.setProperty('--calm',st);halo.style.setProperty('--calm',st);if(w)w.textContent=m.connected?(st>.72?'The lantern is steady.':'The lantern is finding its rhythm.'):'The lantern is waiting.'}
function meditate(){closeModal();screen='meditate';renderMeditation()}
const meditationPhases=[
 {at:0,title:'Arrive',text:'Let the little lantern come into view. Nothing to solve.',voice:'Let the little lantern come into view. Nothing to solve.'},
 {at:.16,title:'Notice',text:'Feel the surface beneath you. Hear one sound. Let the lantern brighten when you notice.',voice:'Feel the surface beneath you. Hear one sound. Let the lantern brighten when you notice.'},
 {at:.34,title:'Soften',text:'Let your attention rest on the lantern. If it wanders, that is okay. Come back when you notice.',voice:'Let your attention rest on the lantern. If your attention wanders, that is okay. Come back when you notice.'},
 {at:.52,title:'Widen',text:'Notice something farther away. Let the room, the screen, and the night all belong here.',voice:'Notice something farther away. Let the room, the screen, and the night all belong here.'},
 {at:.70,title:'Carry',text:'Imagine taking one small piece of this steadiness with you. You do not have to hold it perfectly.',voice:'Imagine taking one small piece of this steadiness with you. You do not have to hold it perfectly.'},
 {at:.88,title:'Return',text:'The lantern stays lit. Take your time coming back to ordinary things.',voice:'The lantern stays lit. Take your time coming back to ordinary things.'}
];
function renderMeditation(){med=med||{running:false,elapsed:0,total:300,last:0,voiceDone:-1};const m=G.S.muse;layout(`<section class="medhead"><button class="back" onclick="UI.go('more')">←</button><p class="eyebrow">THE LANTERN ROOM</p><h1>A quiet little place.</h1><p>Optional Muse feedback makes the lantern respond to your steadiness. Without Muse, it simply follows the timer.</p></section><div class="medcard"><div class="medsky"><div class="medmoon">☾</div><div class="medglow" id="medGlow"></div><div class="medlantern" id="medLantern">🏮</div><div class="medstars">✦ · ✧ · ✦ · ✧</div></div><div class="medcopy"><div class="medphase" id="medPhase">Ready</div><h2 id="medTitle">Begin when you like.</h2><p id="medText">There is no score to beat. The point is to give your attention somewhere kind to return.</p><div class="progress"><i id="medProgress"></i></div><div class="medmeta"><span id="medTime">5:00</span><span id="medMuse">${m.connected?'Muse live':'no Muse'}</span></div><div class="medchoices"><button onclick="UI.setMeditation(180)">3 min</button><button class="selected" onclick="UI.setMeditation(300)">5 min</button><button onclick="UI.setMeditation(600)">10 min</button><button onclick="UI.setMeditation(1200)">20 min</button></div><div class="medactions"><button class="primary" id="medStart" onclick="UI.toggleMeditation()">Begin</button><button class="secondary" onclick="UI.stopMeditation()">Finish</button><button class="secondary" onclick="UI.muse()">${m.connected?'Muse settings':'Connect Muse'}</button></div><label class="toggle"><input id="medVoice" type="checkbox" ${G.S.settings.voice?'checked':''} onchange="G.S.settings.voice=this.checked;G.save()"> gentle spoken guidance</label><p class="fine">The feedback is deliberately subtle: signal quality and movement can change the lantern's glow, while sustained steadiness makes it calmer. No EEG value is interpreted as a mental-health measurement.</p></div></div>`,'more');if(med.running)updateMeditationUI()}
function setMeditation(sec){if(!med)med={running:false,elapsed:0,total:sec,last:0,voiceDone:-1};med.total=sec;med.elapsed=0;med.running=false;med.voiceDone=-1;renderMeditation()}
function toggleMeditation(){if(!med)med={running:false,elapsed:0,total:300,last:0,voiceDone:-1};if(med.running){med.running=false;stopAudio();renderMeditation();return}med.running=true;med.last=performance.now();startAudio();if(G.S.settings.voice)speak('Begin. Nothing to solve.');renderMeditation();med.last=performance.now();requestAnimationFrame(medLoop)}
function stopMeditation(){if(med){med.running=false;med.elapsed=0;med.voiceDone=-1}stopAudio();renderMeditation()}
function medLoop(now){if(!med?.running)return;const dt=(now-med.last)/1000;med.last=now;med.elapsed=Math.min(med.total,med.elapsed+dt);updateMeditationUI();if(G.S.settings.voice)voicePhase();if(med.elapsed>=med.total){med.running=false;stopAudio();G.reward('The lantern stays lit.','ground');toast('The lantern stays lit.');setTimeout(renderMeditation,350);return}requestAnimationFrame(medLoop)}
function updateMeditationUI(){const f=Math.min(1,med.elapsed/med.total),p=meditationPhases.reduce((a,x)=>f>=x.at?x:a,meditationPhases[0]);const title=document.getElementById('medTitle'),text=document.getElementById('medText'),phase=document.getElementById('medPhase'),bar=document.getElementById('medProgress'),time=document.getElementById('medTime'),btn=document.getElementById('medStart');if(!title)return;phase.textContent=p.title;title.textContent=p.title;text.textContent=p.text;bar.style.width=(f*100)+'%';const rem=Math.max(0,med.total-med.elapsed);time.textContent=`${Math.floor(rem/60)}:${String(Math.floor(rem%60)).padStart(2,'0')}`;btn.textContent='Pause';updateMeditationMuse()}
function updateMeditationMuse(){const m=G.S.muse,lan=document.getElementById('medLantern'),glow=document.getElementById('medGlow'),label=document.getElementById('medMuse');if(!lan)return;const q=m.connected?m.quality:.65,st=m.connected?m.steadiness:.45,motion=m.connected?m.motion:0;const calm=Math.max(.18,Math.min(1,.35+st*.65))*q;lan.style.setProperty('--calm',calm);glow.style.setProperty('--calm',calm);label.textContent=m.connected?`Muse · ${Math.round(st*100)}% steady`:'timer only'}
function voicePhase(){const f=med.elapsed/med.total,p=meditationPhases.reduce((a,x)=>f>=x.at?x:a,meditationPhases[0]),idx=meditationPhases.indexOf(p);if(idx!==med.voiceDone){med.voiceDone=idx;speak(p.voice)}}
function speak(t){if(!G.S.settings.voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.86;u.pitch=1.03;u.volume=.55;speechSynthesis.speak(u)}
function startAudio(){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();if(audio._lanterngain) return;const master=audio.createGain();master.gain.value=.018;master.connect(audio.destination);const osc=audio.createOscillator();osc.type='sine';osc.frequency.value=196;osc.connect(master);osc.start();audio._lanterngain=master;audio._lanternosc=osc}catch(_){}}
function stopAudio(){try{if(audio&&audio._lanterngain){audio._lanterngain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.3);setTimeout(()=>{try{audio._lanternosc.stop()}catch(_){}audio._lanterngain=null},350)}}catch(_){}if('speechSynthesis'in window)speechSynthesis.cancel()}
function about(){modal={title:'About the design',body:`<p><b>Lantern is a game first.</b> Its mechanics quietly practice noticing, returning attention, making room for mixed feelings, connection, meaning, and taking the next small step.</p><p>Muse is an optional controller. Its signal can make the lantern, environment and meditation respond in a pleasing way, but the game does not claim that an EEG number is a diagnosis or a measure of emotional health.</p><p>Everything runs locally in the browser. Progress and notebook entries use browser storage. A GitHub Actions build may install development tools, but the published game contains its own runtime files and does not call a service.</p><p class="fine">This is a game prototype, not a substitute for professional care. If playing makes you feel unsafe or unable to orient, pause and use the support available to you.</p>`};renderModal()}
function renderModal(){if(!modal)return;document.body.insertAdjacentHTML('beforeend',`<div class="modalshade" onclick="if(event.target===this)UI.closeModal()"><div class="modal"><button class="close" onclick="UI.closeModal()">×</button><h1>${modal.title}</h1>${modal.body}</div></div>`)}
function closeModal(){document.querySelector('.modalshade')?.remove();modal=null;clearInterval(museTimer)}
function weather(chosen,target){if(chosen===target){G.S.stats.returnWins++;result('You caught it.','The point was not to change the weather. You noticed it, and that was enough.','ground')}else result('No wrong weather.','You noticed a word that did not fit this time. The lantern stays on.','flex')}
function anchor(i){if(!game.picked)game.picked=[];if(!game.picked.includes(game.items[i]))game.picked.push(game.items[i]);if(game.picked.length>=3)result('You came back.','Warmth, water, sound, ground, light, company — ordinary things can be powerful anchors.','ground');else{const b=document.querySelector('.quiet');if(b)b.textContent=`${3-game.picked.length} more, if you want them.`}}
function echo(i,type){if(type==='story')result('You left room for the story.','A thought can feel true without being the only possible future.','flex');else result('You gave it a name.','Facts, feelings, and stories can sit beside one another without having to fight.','meaning')}
function saveNote(){const e=document.getElementById('note');if(G.journal(e.value)){closeModal();toast('Kept in your local notebook.')}else toast('Nothing to save.')}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function exportSave(){const blob=new Blob([G.exportSave()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lantern-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importPrompt(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{if(G.importSave(r.result)){toast('Save restored.');location.reload()}else toast('That save could not be read.')};r.readAsText(f)};i.click()}
function go(x){closeModal();if(x==='meditate')return meditate();screen=x;({home,map,friends,more}[x]||home)()}
function render(){({home,map,friends,more,meditate}[screen]||home)()}
window.UI={go,play,enter,explore,friends,more,journal,muse,about,closeModal,weather,anchor,echo,saveNote,export:exportSave,importPrompt,connectMuse,disconnectMuse,meditate,setMeditation,toggleMeditation,stopMeditation};window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});window.UI.start=()=>{screen='home';home()};
})();
